### ISSUE TITLE
Alternative string concatenation operator

### ISSUE THREAD

**Issue by ainvaltin** [layeh/exprel#1]
I want to save expressions into xml file but in xml "&" has a special meaning and thus "&amp;amp;" must be used. This is kind of inconvenient so what about supporting an alternative operator, ie double pipe "||" like in SQL or perhaps "#" which kind of resembles "+". Or overload the "+" so that it supports string concatenation too?

**Comment by ghost** [comment]
> I want to save expressions into xml file but in xml "&" has a special meaning and thus "&amp;" must be used.

Shouldn't your XML encoder/decoder handle the character substitution automatically for you? Maybe you could use a [CDATA block](https://stackoverflow.com/questions/2784183)?

**Comment by ainvaltin** [comment]
I don't have a UI for entering the expressions, ie the end user uses his editor of choice to create the xml file.
Can't use CDATA, the expressions could be used as either attribute value or tag's value.

**Comment by ghost** [comment]
I'd like to keep the expression syntax as similar to that found in common spreadsheet programs; overloading `+` for concatenation is not something that is commonly done.

Feel free to modify the code to fit your own needs, though.

**Comment by ainvaltin** [comment]
I think that using JOIN function instead of operator is actually acceptable alternative, ie

```
=JOIN(""; "foo"; " bar")
```
