### ISSUE TITLE
Option to pass additional context in Evaluate()

### ISSUE THREAD

**Issue by ainvaltin** [layeh/exprel#2]
I'm in a situation where it would be useful to have additional "execution context" for a custom function (passed to the evaluator via Source). Ie in the user code there is expression like

    =myFunc(someParam)

but the data the `myFunc` should have access to is dependent on the additional constraints only known to the code which evaluates the expression. So I'd like to do something like

	sources := exprel.SourceMap{
		"myFunc": func(c *exprel.Call) (interface{}, error) {
			// make decision based on c.Ctx
		}
	}

	exprel.EvaluateContext(ctx, expression, sources)

Now should the `ctx` parameter be just `interface{}` or `context.Context`?
I guess it would make sense to use the "standard" context.Context althought plain interface would do for my case.

**Comment by ghost** [comment]
While adding a new `EvaluateContext` function may work, it would require several decisions to be made about how it works (e.g. if the context is canceled, should execution of the expression stop?).

Here is another way you can use a context from inside of a source function:

```go
package main

import (
	"context"
	"fmt"

	"layeh.com/exprel"
)

func main() {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	fmt.Println(EvaluateContext(ctx, `=myFunc("param")`))
}

func EvaluateContext(ctx context.Context, expression string) (interface{}, error) {
	sources := exprel.SourceMap{
		"myFunc": func(c *exprel.Call) (interface{}, error) {
			select {
			case <-ctx.Done():
				return nil, ctx.Err()
			default:
			}
			return fmt.Sprintf("myVal: %s", c.String(0)), nil
		},
	}

	return exprel.Evaluate(expression, sources)
}
```

**Comment by ainvaltin** [comment]
Yes, when using `context.Context` then the question is should the `exprel` engine manage the timeout/cancellation or is it user's responsibility... I haven't used the `context.Context` too much myself so I'm not sure what the standard behaviour is.

Your example would work for simple case but I have defined global Sources for common functions which is shared by  different "contexts". Sure I could refactor the funcs which need the context into seprate modules created for each context but it would be easier to pass the context when calling `exprel.Evaluate`.
